version: '3'

services:
  database:
    build: ./database
    image: hoa-database:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  hoa-webhook:
    build:
      context: . # Gradle requires the root context since this is a multi-module gradle build.
      dockerfile: ./webhook/test.dockerfile
    image: hoa-webhook:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - LUMA_API_KEY=${LUMA_API_KEY}
    ports:
      - ${WEBHOOK_PORT}:8080
